[package]
name = "iced_grid"
version = "0.1.0"
authors = ["Alexander van Saase <avsaase [at] gmail.com>"]
edition = "2021"


[dependencies]
iced = "0.10.0"
iced_widget = "0.1.3"

[dev-dependencies]
iced = { version = "0.10.0", features = ["debug"] }
